name: Build (Ngage)

on: [push, pull_request]

jobs:
  build:
    name: Ngage
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Checkout ngage-toolchain
        uses: actions/checkout@v3
        with:
          repository: ngagesdk/ngage-toolchain
          path: ngage-toolchain
          submodules: true

      - name: Setup environment
        run: |
          Set-Variable -Name NGAGESDK -Value ((pwd).ToString() + "/ngage-toolchain")
          echo "NGAGESDK=$NGAGESDK" >> $Env:GITHUB_ENV
          echo "$NGAGESDK/sdk/6.1/Shared/EP0C32/gcc/bin" >> $Env:GITHUB_PATH

      - name: Setup toolchain
        run: |
          cmake -S "$Env:NGAGESDK/setup" `
                -B "$Env:NGAGESDK/setup/build" `
                -G Ninja      
          cmake --build "$Env:NGAGESDK/setup/build"

      - uses: madebr/setup-sdl@master
        with:
          version: "2-latest"
          pre-release: false
          build-type: "Release"
          ninja: true
          cmake-toolchain-file: ${{ env.NGAGESDK }}/cmake/ngage-toolchain.cmake

      - name: Configure (CMake)
        run: |
          cmake -S . `
                -B build `
                -G Ninja `
                -DCMAKE_TOOLCHAIN_FILE=${{ env.NGAGESDK }}/cmake/ngage-toolchain.cmake

      - name: Build (CMake)
        run: cmake --build build --verbose
